### ISSUE TITLE
Don't use built-in fuction names (type, id, ...) as variable names

### ISSUE THREAD

**Issue by guidovranken** [Intelworks/OpenTAXII#4]
This is a proposal in regard to a stylistic property of the source code rather than addressing a real bug or vulnerability.

https://github.com/Intelworks/taxii-server/blob/adding-tests/taxii_server/server.py#L29

I'd recommend not using special names like ```id``` and ```type``` as variable names. The above link is just an example, I've seen more of these overridings in taxii-server. Even though it's legal in Python, these are actually built-in functions:

https://docs.python.org/2/library/functions.html#id
https://docs.python.org/2/library/functions.html#type

In the best case this ambiguity can cause some initial confusion to the human reader of the source code, and in the worst case this may lead to programming errors (if ```type``` is expected to be the built-in function returning the type of a variable when the contents of the local ```type``` variable is expected and vice versa).

**Comment by traut** [comment]
judging by http://landscape.io overview, this is mostly fixed in the current codebase: `id`/`type` are only used as constructor arguments. 

So I consider this issue to be fixed and the approach should be adopted as practice.
